version: 2.1

orbs:
  sam: circleci/aws-serverless@1.0.2
  
jobs:
  build_and_test:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - sam/local-start-api:
          endpoint: test
      - run: bash .circleci/deploy.sh

workflows:
  version: 2
  deploy:
    jobs:
      - build_and_test:
          context: aws_config
