version: 2.1

orbs:
  sam: circleci/aws-serverless@1.0.2
  
jobs:
  build_and_test:
    executor: sam/default
    steps:
      - checkout
      - sam/install
      - run: sam local start-api -t schemas/mysite-SAM.yaml
      - run: bash .circleci/deploy.sh
      
workflows:
  version: 2
  deploy:
    jobs:
      - build_and_test:
          context: aws_config
